### ISSUE TITLE
Can't find site-packages folder

### ISSUE THREAD

**Issue by deroli95** [All4Gis/EquirectangularViewer#1]
Hi there,

I am struggeling to find the path: "D:\OSGeo4W64\apps\Python27\Lib\site-packages" that you gave to paste the ext-libs. Also is it enough to paste those folders into the Plugin Folder of QGIS or is more work necessary?

On top of that I am struggeling to understand how this whole project is set up. Could you possibly provide me the idea in general on which you build this? 

Thanks in advance! 

Best, 

Oliver

**Comment by All4Gis** [comment]
This path is a example,for find it in you computer,open QGIS and open the Python console and try with this for print the path:
`import site; site.getsitepackages() `

You only need open this: /Project_example/example_project.qgs and remember put the correct images path in the shapefile,absolute path is necessary

**Comment by All4Gis** [comment]
And check the new plugin and test project example,and read the new readme.md file

**Comment by All4Gis** [comment]
Find site-packages path? Can I close this issue?
