### ISSUE TITLE
White viewer

### ISSUE THREAD

**Issue by valeriodeluca** [All4Gis/EquirectangularViewer#11]
Hi Francisco, thank you for this great QGIS plugin.
Everything go fine but when I click on points the viewer get me white all.
Any troubleshoot about that?
This issue appens with example_project.qgz. The name of points shapefile and the coloums' name right match the confing.py in "C:\Users\***\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\EquirectangularViewer\config.py".
Thank you! :)

**Comment by All4Gis** [comment]
Hi,, mmmm... Are you using a proxy? If you open this address in a browser, will you see anything, http://127.0.0.1:1520/viewer.html?

**Comment by valeriodeluca** [comment]
Thanks for your fast reply, [http://127.0.0.1:1520/viewer.html](http://127.0.0.1:1520/viewer.html) says me ERR_CONNECTION_REFUSED.
I tried switch off Windows Defender Firewall but same issue.

The QGIS py console check about requirements go fine, no errors:
from PIL import Image
from cefpython3 import cefpython

**Comment by All4Gis** [comment]
if you open the plugin dialog and without closing it, open a browser you should see the viewer. If it says, conection refused, I don't know right now how to activate it in python/win.

You can also change the port in the config.py file to a port that you know you can connect, change the 1520 to whatever .

**Comment by valeriodeluca** [comment]
I tried switch from 1520 to 2520 in config.py but same issue.
Trying to open port 1520 in Windows Defender Firewall [(https://www.youtube.com/watch?v=xMGPyZtdP00)](https://www.youtube.com/watch?v=xMGPyZtdP00) but not works yet.

**Comment by valeriodeluca** [comment]
Another try checked: install from QGIS Pllugin Repository and from ZIP file [(https://github.com/All4Gis/EquirectangularViewer/releases/download/1.2/EquirectangularViewer.zip)](https://github.com/All4Gis/EquirectangularViewer/releases/download/1.2/EquirectangularViewer.zip), but same issue.

**Comment by All4Gis** [comment]
I'll have to try with a windows machine I guess because on linux I don't have that problem.Thanks for your feedback

**Comment by All4Gis** [comment]
This ticket is related with cefpython. We can close it as cefpython has been deleted in the new 1.3 release.This release has been financed by @valeriodeluca, thanks
https://github.com/All4Gis/EquirectangularViewer/releases/tag/1.3
