### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'argv'

### ISSUE THREAD

**Issue by victorteixeira143** [All4Gis/EquirectangularViewer#12]
![image](https://user-images.githubusercontent.com/86630743/123705109-dea62580-d83c-11eb-976a-0723f1dc42f0.png)

I am encountering this error when using the equirectangular plugin in the test file, do you know how to solve it?

**Comment by All4Gis** [comment]
check this,

https://github.com/All4Gis/EquirectangularViewer/issues/4
https://github.com/All4Gis/EquirectangularViewer/issues/7

**Comment by valeriodeluca** [comment]
@victorteixeira143 as said @manumanul here: 
https://github.com/All4Gis/EquirectangularViewer/issues/4#issuecomment-707710053
also for me the plugin works if before clicking on the plugin icon I run this line of code in the QGIS Python console:
```sys.argv = []```

**Comment by victorteixeira143** [comment]
Thank you @All4Gis and @valeriodeluca!
It works after run the code "sys.argv = [] in" QGIS Python console

**Comment by All4Gis** [comment]
This ticket is related with cefpython. We can close it as cefpython has been deleted in the new 1.3 release.This release has been financed by @valeriodeluca, thanks
https://github.com/All4Gis/EquirectangularViewer/releases/tag/1.3
