### ISSUE TITLE
Ubuntu. Import cefpython Exception: Python version not supported: 3.8

### ISSUE THREAD

**Issue by valeriodeluca** [All4Gis/EquirectangularViewer#13]
In Ubuntu 20.04 importing cefpython with python 3.8 raised:
Exception: Python version not supported: 3.8.5

Maybe because cefpython in Linux is supported to Python 3.4 / 3.5 / 3.6 / 3.7:
https://github.com/cztomczak/cefpython

In Ubuntu 20.04, is there a way to change default Python in QGIS?
Usually in Ubuntu 20.04 installing QGIS 3.20.x Odense you get Python 3.8.5. How switch to Python 3.7 as default Python in QGIS?

**Comment by All4Gis** [comment]
I'll work on this tomorrow. I will give you a solution asap

**Comment by All4Gis** [comment]
This ticket is related with cefpython. We can close it as cefpython has been deleted in the new 1.3 release.This release has been financed by @valeriodeluca, thanks
https://github.com/All4Gis/EquirectangularViewer/releases/tag/1.3
