### ISSUE TITLE
Zoom error overlay effect

### ISSUE THREAD

**Issue by valeriodeluca** [All4Gis/EquirectangularViewer#14]
I'm on Windows 10, QGIS 3.12.
When I click on a point Equirectangular Viewer opens correctly.
But if I try to zoom in, zoom out or full screen in Equirectangular Viewer I get an overlay effect like that:

1. No Zoom, no overlay effect
![image](https://user-images.githubusercontent.com/3809277/123959840-e8e83100-d9ae-11eb-9392-0731361b1584.png)

2. Zoom Out (Minus), overlay effect
![image](https://user-images.githubusercontent.com/3809277/123959915-ff8e8800-d9ae-11eb-86b9-f10eae9537e3.png)

3. Zoom In (Plus), overlay effect
![image](https://user-images.githubusercontent.com/3809277/123960065-2947af00-d9af-11eb-8891-1ef75eac1f42.png)

4. Full Screen, overlay effect
![image](https://user-images.githubusercontent.com/3809277/123961257-71b39c80-d9b0-11eb-8fde-2b0db70193af.png)

**Comment by All4Gis** [comment]
This ticket is related with cefpython. We can close it as cefpython has been deleted in the new 1.3 release.This release has been financed by @valeriodeluca, thanks
https://github.com/All4Gis/EquirectangularViewer/releases/tag/1.3
