### ISSUE TITLE
EPSG 3857

### ISSUE THREAD

**Issue by valeriodeluca** [All4Gis/EquirectangularViewer#17]
It would be handy to have the ability to set at least the 3857 reference system on QGIS while using the EV plugin.

The 4326 reference system that the EV plugin works with provides a somewhat enlarged view of the base such as OSM, while the 3857 favors a less distorted view than the 4326.

Currently, if you try to use the EV plugin with the 3857 system, as soon as you click on a point to open the Viewer, the map moves to the coordinates 0,0 (Equator / Greenwich intersection).

I understand that it is complicated to have the ability to set up many reference systems that work with the EV plugin, but it would be useful to have at least the 3857 system.

![3857](https://user-images.githubusercontent.com/3809277/125925053-b2f578e2-4873-4095-aea5-ea727d3982c1.JPG)

**Comment by All4Gis** [comment]
Fixed in version 1.4. This feature has been funded by Valerio de Luca. Thanks
