### ISSUE TITLE
General steps for use it

### ISSUE THREAD

**Issue by deroli95** [All4Gis/EquirectangularViewer#2]
Can't use the Plugins in QGIS. It seems that metadata files are missing for both libraries? 

I also don't get the part with the server that is to be started with Python, how and where is this supposed to happen? Within QGIS?

**Comment by All4Gis** [comment]
The metadata file is not missing.Can attach the error screenshot?

For watch the server config only you need to inspect the config.py

**Comment by mnaveedsaeed** [comment]
![pro](https://user-images.githubusercontent.com/32033256/30520006-f0db89bc-9bbd-11e7-8cec-31c3535fb7fa.png)
Any help for this fix?

**Comment by All4Gis** [comment]
Please check that you have in **".qgis2/python/plugins"** the EquirectangularViewer folder.
In my case for example is this : **C:\Users\fjraga\.qgis2\python\plugins**

![s_1](https://user-images.githubusercontent.com/8123225/30530925-265dd260-9c4b-11e7-87ac-b82b6fc23444.PNG)

And this folder the plugin files.

![s_3](https://user-images.githubusercontent.com/8123225/30531012-a657dc54-9c4b-11e7-904c-637402b1cd1f.PNG)

Abd the other Mandatory step is copy cefpython3 in the site-package,for example in my case : 
**C:\OSGeo4W64\apps\Python27\Lib\site-packages**

![s_2](https://user-images.githubusercontent.com/8123225/30530959-524d3e10-9c4b-11e7-98f7-8ddece36cb6f.PNG)


Have you this folder structure?and install it cefpython correctly?

**Comment by mnaveedsaeed** [comment]
>>install it cefpython correctly?

I have perfectly placed it on good location but I have error "global name 'cefpython' is not defined". What do you mean by install CefPython?

**Comment by All4Gis** [comment]
you need copy the correct cefpython3 folder.You're QGIS installation is 32 or 64 bits?
If is 32 bits need copy this :  [x86](https://github.com/All4Gis/EquirectangularViewer/tree/master/ext-libs/x86/cefpython3)
and if you have the x64 QGIS version is this : [x64](https://github.com/All4Gis/EquirectangularViewer/tree/master/ext-libs/x64/cefpython3)

**Comment by mnaveedsaeed** [comment]
>Please check that you have in ".qgis2/python/plugins" the EquirectangularViewer folder.
Done, see Image:
![plugins](https://user-images.githubusercontent.com/32033256/30541995-1236d772-9c97-11e7-9bef-416b365dcd49.png)

>copy cefpython3 in the site-package:
Done for 64 bit, see image:
![plugins](https://user-images.githubusercontent.com/32033256/30542075-58858b2e-9c97-11e7-86d7-9e829d81c18e.png)

For example project, files are placed at good path, see image:
![path](https://user-images.githubusercontent.com/32033256/30542373-94e73c42-9c98-11e7-94c7-417ecf1e0f13.png)

But when i open example project, i have following error:
2017-09-18T17:37:40	1	Traceback (most recent call last):
			  File "C:/Users/Naveed/.qgis2/python/plugins\EquirectangularViewer\Geo360.py", line 133, in run
			    self.StartCefPython()
			  File "C:/Users/Naveed/.qgis2/python/plugins\EquirectangularViewer\Geo360.py", line 89, in StartCefPython
			    cefpython.GetModuleDirectory(), "subprocess")
			NameError: global name 'cefpython' is not defined

Any fix for this?

**Comment by All4Gis** [comment]
the second image is not correct,please fix it

**Comment by All4Gis** [comment]
Finally, I have managed to get the same error.
I will solve

**Comment by All4Gis** [comment]
Finally, I have obtained the same error.

**Steps:**

Please,install cefpython using pip .
`pip install cefpython3`

And open again the project, note that the layer name is **photos_map_4326** and not **Photos_map_4326** ,if you want change the layer name,need change **layer_name**  value in **config.py** file and open it again.

tested in windows 10 and QGIS 2.18.13

**Comment by mnaveedsaeed** [comment]
pip install cefpython3

Now working. you know another way to install?

**Comment by All4Gis** [comment]
Or using this or maybe using python,for example.

```
import pip
pip.main(['install','cefpython3'])
```

Show the wiki project [Download_CEF3_Windows](https://github.com/cztomczak/cefpython/wiki/Download_CEF3_Windows),for more information.

**Comment by deroli95** [comment]
For me using 'pip2.7' solved the problem of cefpython, because QGIS runs on Python2.7 and I am using Python3 as default. I don't know in how far this is applicable for Windows.

The problem occuring for me is now that the pictures are not found by the plugin and if I try to use the plugin in another project, I get asked to "Upload the photo-layer". What does that mean?

Did you tried placing projec files on path defined in shp?

What do you mean?

I have the absolute paths to the images in my shp file. Opening via an action works.

**Comment by justnave** [comment]
Did you tried placing projec files on path defined in shp?

Muhammad Naveed Saeed

Cell: +92 322 4296004

Skype, Messener, Telegram, LinkedIn, Gmail: mnaveedsaeed

**Comment by deroli95** [comment]
What do you mean?

I have the absolute paths to the images in my shp file. Opening via an action works.

**Comment by All4Gis** [comment]
what is the name of the layer in the TOC?photos_map_4326 OR **P**hotos_map_4326?Have you capitalize the firts letter?
Open the config.py and replace **layer_name** value for your layer "**show**" name.

**Comment by All4Gis** [comment]
what is the name of the layer in the TOC?photos_map_4326 OR **P**hotos_map_4326?Have you capitalize the firts letter?
Open the config.py and replace **layer_name** value for your layer "**show**" name.

**Comment by deroli95** [comment]
I can start the plugin now. Unfortunately it tells now, that there is no picture.

Additionally I get set from this position: 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/23140150/30589507-05cc4784-9d3b-11e7-9b21-593f267cc75e.png">

To this:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/23140150/30589525-1a53d2e4-9d3b-11e7-819f-6186b0a38837.png">
 
which is in the middle of nowhere. Any idea where my mistake is?

Has the file to have a special attribute? At the moment I have the Path, lat & lng stored in my layer attribute file.

**Comment by All4Gis** [comment]
check the system reference,is important that use epsg:4326 ,put the correct path in layer,and all columns that the plugin need,copy the original shapefile structure and debug the plugin for find the errors.
This is a experimental plugin,isn't tested in mac for example.

**Comment by All4Gis** [comment]
solve it the problems??Can close this issue?

**Comment by mnaveedsaeed** [comment]
For mine, yes it was solved. Though wanted to ask that if there a way i can
do geocode/place points using this Viewer or directly on viewer?

**Comment by All4Gis** [comment]
I would not know to tell you, it is already a other development. The viewer only serves to see points not to add new points to your shapefile.
Close this issue

regards

**Comment by miguel-vivanco** [comment]
I could fix the issue installing the package cefpython3

1. Open OSGeo4W shell (packed with QGIS in the start menu)
2. Type py3_env. This should print paths of your QGIS Python installation.
3. Use Python’s pip to install the library of your choice: python -m pip install cefpython3

I hope this help you.
