### ISSUE TITLE
Qgis browser panel continuous loading

### ISSUE THREAD

**Issue by encleadus** [All4Gis/EquirectangularViewer#20]
First, thank you for the plugin, it works great.
I am trying to use qgis on windows terminal server on windows server 2016, so I can have instant speed access to my database and other people can log in to it.
For some reason the equirectangular viewer is not working here, but only in the qgis browser panel. If I open a chrome browser on localhost 1520 I can see the pictures.

The terminal server runs IIS as service and I think there must be something between that and the plugin? Like blocking server side javascript or something like that. Do you have any experience in this kind of issues?

**Comment by All4Gis** [comment]
I'm sorry I can't help you, check your connections, but I have no experience with what you say and can't reproduce it.
