### ISSUE TITLE
Using GeoJSON and source

### ISSUE THREAD

**Issue by hdorn** [All4Gis/EquirectangularViewer#22]
I want to use the plugin EquirectangularViewer with my own GeoJSON layer.

When I inspect the example project's layer, it gives a source under 'Layer Properties -> Information'. When I add my own layer with GeoJSON the source doesn't show up.

Could you give me a hint how I add this source?

**Comment by All4Gis** [comment]
Hi , sorry delay,mmmm....I don't understand the problem, because this is related with QGIS I think and not with this project
