### ISSUE TITLE
Can it be docked to QGIS planel.

### ISSUE THREAD

**Issue by anmolbhardwaj5** [All4Gis/EquirectangularViewer#24]
I liked the plugin very ,uch . The issue I am facing is I have to change the window tabs again and again . I was asking can it be fixed to side (or made dockable) for ease of use. I also searched for qgis codes to make it dockable. I wasable to find this code
self.iface.addDockWidget( Qt.RightDockWidgetArea, your_object) 

Now I do knot know where to paste it and also I am not able to pin point the object calling Equirectangular viewer. 
Thanks in advance

**Comment by All4Gis** [comment]
Hi, the last version is a docked QGIS panel 
https://github.com/All4Gis/EquirectangularViewer/blob/master/code/Geo360.py#L150C24-L150C37

self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.orbitalViewer)

I you want the panel in the right area, need to change Bottom to Right

**Comment by anmolbhardwaj5** [comment]
Thank you , it worked like a charm. I was using older version of QGIS . Changing the version solved the problem 
Regards
Anmol
