### ISSUE TITLE
AttributeError: module 'sys' has no attributre 'argv'

### ISSUE THREAD

**Issue by manumanul** [All4Gis/EquirectangularViewer#4]
I successfully installed your plugin 'EquirectangularViewer' in QGIS, but I am unfortunately unable to use it.
Each time when I click on the corresponding icon, 
![grafik](https://user-images.githubusercontent.com/61459953/95468151-82356a00-097e-11eb-8956-ecd1da3d3e38.png)
it gives me the following error:
![grafik](https://user-images.githubusercontent.com/61459953/95987290-7f77c080-0e27-11eb-9d4d-0bd7756e3d73.png)
I precisely followed your installation guidelines (https://www.youtube.com/watch?v=iJhh0IWijL0&feature=youtu.be) and downloaded your test project (https://github.com/All4Gis/EquirectangularViewer/tree/master/code/Project_example) to test the plugin . Everything seems to work fine, until I actually want to use it and click on that icon.

I tried with both QGIS versions 3.10.9 and 3.14.15.

Any ideas? Any help much appreciated (as this plugin really seems very promising :))!

**Comment by All4Gis** [comment]
check this https://stackoverflow.com/questions/49195814/cefpython-wont-initialized-when-called-from-an-application

**Comment by manumanul** [comment]
Thanks for the answer, according to this stackoverflow question my python environment seems to behave strangely.
Apparently it could be working when calling "sys.argv  = []" before calling "cef.Initialize" within my code. I tried to edit the __init__.py-file:

![grafik](https://user-images.githubusercontent.com/61459953/95739795-adc09900-0c8b-11eb-8feb-70ff421f3a7a.png)

, but without success. Where should I run this line of code?

**Comment by All4Gis** [comment]
That you have to change the python installation of QGIS, inside there you will have the cefpython module. That line you have to put there

**Comment by manumanul** [comment]
Yeah it worked! Indeed, I had to run this line of code from the python console within QGIS before clicking on the EquirectangularViewer-icon. 
However, it is a bit annoying to type this line of code anytime before using this plugin - do you have any other suggestions?

**Comment by All4Gis** [comment]
You have to change it in the cefpython installation. You don't have to run it from QGIS every time

**Comment by manumanul** [comment]
Where is that cefpython installation of QGIS?

**Comment by All4Gis** [comment]
check this https://gis.stackexchange.com/questions/141320/installing-3rd-party-python-libraries-for-qgis-on-windows and search the cefpython folder

**Comment by manumanul** [comment]
I found that folder, but I don't know what file I have to edit. When I edit "init.py", nothing happens. I thought it might be the "cefpython_py37.pyd"-file but I cannot read it properly due to some encoding issues.

![grafik](https://user-images.githubusercontent.com/61459953/95987116-45a6ba00-0e27-11eb-86f4-bc2cbb77ae83.png)

**Comment by All4Gis** [comment]
I can't help you anymore, I can't reproduce this error If you put it in the init.py it should work for you. Sorry

**Comment by manumanul** [comment]
ok, too bad, maybe I need to try again. I will close this issue anyways since I got it running (at least by running this line of code each time within the python console of QGIS). And thanks for your help, I much appreciate that!

**Comment by valeriodeluca** [comment]
> Yeah it worked! Indeed, I had to run this line of code from the python console within QGIS before clicking on the EquirectangularViewer-icon.
> However, it is a bit annoying to type this line of code anytime before using this plugin - do you have any other suggestions?

@manumanul Also for me the plugin works if before clicking on the plugin icon I run this line of code in the QGIS Python console:
```sys.argv = []```
