### ISSUE TITLE
Cant set path as URL

### ISSUE THREAD

**Issue by zedpr0** [All4Gis/EquirectangularViewer#8]
I would like to set the path as a url, but when I change the Geo360Dialog filed edit the auction to pass the path(url) unchanged. the url gets passed by I still get the error "there is no associated image", and the image not available placeholder.

I am using the example_project and the only changes I have made are to the Geo360Dialog.py file as shown below:

original:

    def GetImage(self):
        ''' Get Selected Image '''
        try:
            path = qgsutils.getAttributeFromFeature(
                self.selected_features, config.column_name)
            if not os.path.isabs(path):  # Relative Path to Project
                path_project = QgsProject.instance().readPath("./")
                path = os.path.normpath(os.path.join(path_project, path))
        except Exception:
            qgsutils.showUserAndLogMessage(
                u"Information: ", u"Column not found.")
            return

        qgsutils.showUserAndLogMessage(u"Information: ", str(
            path), onlyLog=True)
        return path

changed:

    def GetImage(self):
        ''' Get Selected Image '''
        try:
            path = qgsutils.getAttributeFromFeature(
                self.selected_features, config.column_name)
            print(path)
            if not os.path.isabs(path):  # Relative Path to Project
                #path_project = QgsProject.instance().readPath("./")
                path = path #os.path.normpath(os.path.join(path_project, path))
                print(path)
        except Exception:
            qgsutils.showUserAndLogMessage(
                u"Information: ", u"Column not found.")
            return

        qgsutils.showUserAndLogMessage(u"Information: ", str(
            path), onlyLog=True)
        return path

I was hoping maybe someone could help me out and show me how to set the path for the equirectangular images as a URL so I can host them on a server. Thanks in advance.

**Comment by All4Gis** [comment]
Hi,

Apart from change this method you will also have to change the method for copying the image from a server in the `CopyFile` method.

You will also have to adapt some checks in the code, for example if the path to the image exists.

**Comment by zedpr0** [comment]
Thank you so much for the reply, I think that's way out of my python level. I found the CopyFile method in the Geo360Dialog.py file but have no idea where to start or what to change.
