### ISSUE TITLE
Do I need a specific format for my shapefile to works on the plugin?

### ISSUE THREAD

**Issue by clibson** [All4Gis/EquirectangularViewer#9]
Thank you so much your hard work for plugin, its excellent!
After many hours    to install the plugin, because I had a problem with python, I installed but works just in your project sample.
I have a point shapefile with 360 photos collected ith GoPro Fusion. 
The table of contents of my shapefile is larger than your case file. Is it a problem? 
![image](https://user-images.githubusercontent.com/11863754/122080004-4b98d480-cdd4-11eb-9265-19fe1f1ce902.png)

**Comment by All4Gis** [comment]
Nopes, the important part is this file https://github.com/All4Gis/EquirectangularViewer/blob/master/code/config.py
You need modify this file with your column names in your shapefiles and probably the data type as well

**Comment by clibson** [comment]
Thanks! I changed the table of contents on my shapefile and the data type is like your sample, but right now I have a problem with the shape. 

![image](https://user-images.githubusercontent.com/11863754/122136139-3cd41100-ce18-11eb-9441-b1d79b638164.png)

I don't know what I do wrong.

![image](https://user-images.githubusercontent.com/11863754/122136371-be2ba380-ce18-11eb-97e5-9549c82a27d6.png)

**Comment by All4Gis** [comment]
You have to change the configuration file of the Qgis plugin, not the Github one. Search for the plugin, change the file and restart QGIS. https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location

And the other thing is that your variable in layer name is "divisa_str**eet**" and your layer name in the TOC is "divisa_str**ett**" , is not the same.

**Comment by clibson** [comment]
Thank you one more time! 

I changed the configurations following your orientations. Its worked! But, my images no-showed.

![image](https://user-images.githubusercontent.com/11863754/122306046-30b28700-cede-11eb-9b89-c4f722bd4f53.png)

I checked the address of my photos on the table of contents and it was right. 

Do I need to put on the photos (and/or project files) in the plugin folder as well? Same as your sample project.

![image](https://user-images.githubusercontent.com/11863754/122306660-3eb4d780-cedf-11eb-9b54-47228af20dc9.png)

Thank you for your patience and quick answer!

**Comment by All4Gis** [comment]
It is not necessary for the images or the project to be in the same path as the project. What I can think of is that it could be a problem with the path, try changing your path for example, D:/MY/PHOTO... to D:\MY\PHOTO... a and above all check that the example project works for you. If it works, the problem is in your layer, maybe field type, or problems with your path.

**Comment by clibson** [comment]
Thanks, Mr. Raga! 
I will follow your recommendations.
How do you do picture files? On the QGis I use ImportPhots plugin.

**Comment by All4Gis** [comment]
There is no method for that in particular, if that plugin works for you, great, keep using it.
